// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plmvkzlwsbbfilbzyjce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbXZremx3c2JiZmlsYnp5amNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDI3NDcsImV4cCI6MjA3MTc3ODc0N30.LpeemZyIT4YkiSrmMfbqNrEEzHNezTizF5gxVA1NtMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});